import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Social from "@/components/Social";
import { ThemeProvider } from "@/context/ThemeProvider";
// import MouseTrailer from "@/components/MouseTrailer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kunal Singh",
  description: "Generated by Kunal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <MouseTrailer /> */}
          <Social />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
